version: '3.8'

name: redis
services:
  redis:
    image: redis:latest
    container_name: redis_container
    # restart: always
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/redis/data